### ISSUE TITLE
Move printMatrix core functionality to Grid

### ISSUE THREAD

**Issue by oscarnava** [oezg/minesweeper-kt#3]
This functionality should also be part of the `Grid` class but to respect the Functional Programming approach, Grid should return a value rather than printing the grid itself (a perfect candidate for the `asString` method) and the Minesweeper class can then take that value and print the grid state.

Another important comment: Minesweeper is accessing the `matrix` member directly here, which goes against the encapsulation principle. Imagine that you decide to change the approach taken **_internally_** in Grid and completely get rid of that matrix value. You would break any code which uses that `matrix` but is external to `Grid`. This is why those members that are part of the inner workings of the class **_and no one should be dealing directly with them_** should be either `private` or `protected`. And if you need to give access to the value it should be through a getter, but no setter (like we did in the Cell class for the isExplored value, for example).

https://github.com/oezg/minesweeper-kt/blob/642d5b87c6a0dec323cc6816c0f5208fdadfd8d7/Minesweeper.kt#L36-L48

**Comment by oezg** [comment]
I think I achieved it. `grid.asString(state)` returns a List of Strings.
