### ISSUE TITLE
Use a specific class for coordinates instead of a generic class like Pair<Int,Int>

### ISSUE THREAD

**Issue by oscarnava** [oezg/minesweeper-kt#4]
Something like:

```kotlin
data class Coordinate(x: Int, y: Int)

// or 

data class Position(row: Int, col: Int)
```

Reasons:
- For readability: It's easier to understand the functionality of any of those classes than the generic `Pair`.
- For precision: In a `Pair<Int,Int>` you can't easily know which one of the Ints is the horizontal component, and which is the vertical one.
- For functionality: We can easily add specific functionality like validation, or computing the distance between two `Coordinates`. We could use an extension function for a `Pair<Int,Int>` but that would apply for any Pair of Ints, regardless of functionality.

**Comment by oezg** [comment]
I created a Position class in its own file.
