### ISSUE TITLE
State does not refer to the Minesweeper game, but to the Grid

### ISSUE THREAD

**Issue by oscarnava** [oezg/minesweeper-kt#5]
If you think about it, the State enum describes the state of the Grid, not of the game.

https://github.com/oezg/minesweeper-kt/blob/642d5b87c6a0dec323cc6816c0f5208fdadfd8d7/Minesweeper.kt#L6-L11

A case in point: `Grid` shouldn't use an enum from the containing class. This creates a **_tight coupling_** between the two classes, which is very bad. 😬

https://github.com/oezg/minesweeper-kt/blob/642d5b87c6a0dec323cc6816c0f5208fdadfd8d7/Grid.kt#L20-L33

**Comment by oezg** [comment]
I am in the process of moving the State into Grid however Minesweeper is left with almost no functionality whereas Grid has almost all functionality.

**Comment by oscarnava** [comment]
As long as the responsibility is divided correctly, it will be OK. And don't worry because there might be more changes. 😅 We'll cross the bridge when we get there.

**Comment by oscarnava** [comment]
Maybe we should have two different internal `States`, one for `Grid` and one for `Minesweeper`, because:

- For `Grid`, the states `Win` and `Loss` have no meaning since those are reached after a move, and `Grid` shouldn't deal with game results.
- For `Minesweeper`, the states `NotExplored` and `NotFinished` are not relevant since `Grid` should be keeping track of those.

BTW, I don't get the use of the state `NotFinished`. Could you explain what it indicates, and why it's needed?

**Comment by oezg** [comment]
Thank you for your opinion!
I used NotExplored to to denote the state before the mine positions were determined. They are determined once the user explores a cell because I don't want the first cell explored to be a mine. Now I got rid of it by checking if the set of mine positions is empty or not.
