### ISSUE TITLE
There are some things I don't like about the method `explore`

### ISSUE THREAD

**Issue by oscarnava** [oezg/minesweeper-kt#7]
There are some things I don't like about the method `explore`:

- It's making decisions about the state of **_the game_**, not just **_the grid_**, I mean, the grid shouldn't decide if the game is won or lost, that's the responsibility of Minesweeper.
- Lines `28` to `31` produce a **_side effect_**. That's a no-no in functional programming.
- The grid cells are changing their internal state, which in turn changes the grid's state, making the grid invariant. Although this is a possible solution, it's not ideal. The pure functional approach would be that when we explore the grid it would return a brand new grid with the latest state reflected.

Are you up to fix these issues? I've been thinking of an approach but it would be much better if you do it; it's an amazing learning opportunity and I don't want to take that from you, even though I find it an interesting challenge. 😉

https://github.com/oezg/minesweeper-kt/blob/6ef728f9108c55e023ae1e890f2145ed35ab8e00/Grid.kt#L18-L38

**Comment by oezg** [comment]
Good morning! I am trying to fix this issue.

**Comment by oezg** [comment]
still working on it, not finished yet.

**Comment by oscarnava** [comment]
No hurries. Focus on solving it as best as you can, with no time pressure.

**Comment by oezg** [comment]
I give up for now. I tried but there is a bug, I cannot debug it.

**Comment by oscarnava** [comment]
Don't worry, you'll get there. 😁
Are you using IntelliJ? Maybe we should create some tests, BTW.

**Comment by oscarnava** [comment]
I sent you a PR yesterday fixing two bugs.

**Comment by oezg** [comment]
I saw it and started to work on it but I am very busy with kids. I will
keep working on it as soon as I can.

**Comment by oscarnava** [comment]
No worries. Enjoy your time with the kids. 😁

BTW, I think you are complicating things a bit. I've created my own
version, so maybe I can send it your way later and we can compare
approaches.

**Comment by oscarnava** [comment]
BTW, let me propose a change in how we are doing this: Please send me a PR with your changes **_BEFORE_** merging so that I can review your code and suggest changes or improvements, otherwise we are losing the purpose of PRs.

**Comment by oezg** [comment]
Hello, I will gladly do it. I am a little novice. How can I send you a PR?

**Comment by oscarnava** [comment]
Let me create a step-by-step guide, but mainly the steps are:

1. Create and switch to a new branch with the command `git checkout -B <branch-name>`
2. Commit any changes to this new branch
3. Push the new branch with the command `git push -u origin <branch-name>`
4. Go to the repo at GitHub.com; you will get a suggestion to create a new PR using the newly pushed branch. Click on `Create PR`.
5. Add a comment and assign the PR review to anyone you like; me, for example. 😉

That's essentially it. The issue right now is that you've already merged the changes in `main` so you might want to undo the merges with the command `git reset --soft HEAD~1` The last `1` is the number of commits you want to undo, and the --soft is to tell git you want to keep the changes made. Don't forget it or you could lose your changes.

Check this for more info: https://www.datacamp.com/tutorial/git-reset-revert-tutorial

**Comment by oscarnava** [comment]
I've temporarily removed my branch so you don't get confused. Remember you need to indicate you want to merge your new branch into `main`, not vice versa.

**Comment by oezg** [comment]
Thank you. I am closing the issue here but will go on to find a solution.
